### ISSUE TITLE
Milestone 2: Design the App

### ISSUE THREAD

**Issue by jcairn02** [UBC-MDS/DSCI-532_2024_7_ds-compensation#22]

**Comment by dorisyycai** [comment]
We brainstormed some improvement for milestone 3 based on the feedback from Joel in lab today.

 
1. Boxplot by Avg Salary vs Remote Ratio
2. Boxplot by Avg Salary vs Experience Level
3. Top X Job Title by highest avg salary paid
4. World Map, and coloured by Avg Salary
5. Histogram of salary distribution
6. Global Filter – Continent
7. Local Filter – X Top jobs by highest salary slider
8. List of countries included in the continent – dropdown
