### ISSUE TITLE
Milestone 2 : Make app functional (minimum of six input + output components in total (e.g. 2 inputs (widgets) + 4 outputs (charts, tables, text, etc.)), with a minimum of two of each (so you can't have 0 inputs and 6 outputs).)

### ISSUE THREAD

**Issue by jcairn02** [UBC-MDS/DSCI-532_2024_7_ds-compensation#23]

**Comment by dorisyycai** [comment]
We will continue developing the dashboard based on the feedbacks from the lab today. We will improve our dashboard by implementing the following items in Milestone 3.
 
1. Boxplot by Avg Salary vs Remote Ratio
2. Boxplot by Avg Salary vs Experience Level
3. Top X Job Title by highest avg salary paid
4. World Map, and coloured by Avg Salary
5. Histogram of salary distribution
6. Global Filter – Continent
7. Local Filter – X Top jobs by highest salary slider
8. List of countries included in the continent – dropdown
