### ISSUE TITLE
Feedback from Joel M4

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_7_ds-compensation#73]
Implement one major and four minor

Major:
- [x] #85

Minor:
- [x] #76
- [x] #77
- [x] #78
- [x] #79
- [x] #80
- [x] #81
- [x] #94
- [x] #82

**Comment by wqxxzd** [comment]
Map zoom out limitation was left because we couldn't figure out an optimal solution

**Comment by shoinagaki** [comment]
Thank you for your feedback Joel.
